[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

disableKinds = ["RSS"]

[params.katex]
enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]


[[menu.main]]
  name = "STAP-primitives"
  url = "/STAP-primitives/"
  weight = 2